package com.fap.common.config;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Properties;
import java.util.stream.Stream;
import java.util.zip.ZipEntry;
import java.util.zip.ZipFile;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assumptions.assumeThat;

/**
 * Inspects the deployable jar that {@code package} produced before this suite ran. These are
 * properties of the artifact, not of the running application, so no Spring context or database.
 */
class PackagedJarIT {

	private static Path jar;

	@BeforeAll
	static void locateRepackagedJar() throws IOException {
		try (Stream<Path> files = Files.list(Path.of("target"))) {
			jar = files
					.filter(path -> path.getFileName().toString().endsWith(".jar"))
					.filter(path -> !path.getFileName().toString().endsWith(".original"))
					.findFirst()
					.orElse(null);
		}
		assumeThat(jar).as("repackaged jar in target/ (run through `mvnw verify`)").isNotNull();
	}

	/** Demo accounts and e2e fixtures are local-only; a shipped jar must not carry them. */
	@Test
	void seedDataIsNotPackaged() throws IOException {
		List<String> seedEntries = entries().filter(name -> name.contains("db/seed/")).toList();

		assertThat(seedEntries).isEmpty();
	}

	@Test
	void migrationsArePackaged() throws IOException {
		assertThat(entries()).contains("BOOT-INF/classes/db/migration/V1__create_fap_schema.sql");
	}

	@Test
	void buildInfoNamesTheArtifact() throws IOException {
		try (ZipFile zip = new ZipFile(jar.toFile())) {
			// The repackager lifts build-info.properties out of BOOT-INF/classes to the jar root.
			ZipEntry entry = zip.getEntry("META-INF/build-info.properties");
			assertThat(entry).as("build-info.properties generated by spring-boot:build-info").isNotNull();
			Properties buildInfo = new Properties();
			try (InputStream input = zip.getInputStream(entry)) {
				buildInfo.load(input);
			}
			assertThat(buildInfo.getProperty("build.artifact")).isEqualTo("fap-backend");
			assertThat(buildInfo.getProperty("build.version")).isNotBlank();
		}
	}

	private static Stream<String> entries() throws IOException {
		try (ZipFile zip = new ZipFile(jar.toFile())) {
			return zip.stream().map(ZipEntry::getName).toList().stream();
		}
	}
}
