-- Rollback for FAP Backend v1 Oracle schema.
-- Drops child tables first, then parent tables.

DROP TABLE refresh_tokens CASCADE CONSTRAINTS;
DROP TABLE system_settings CASCADE CONSTRAINTS;
DROP TABLE audit_logs CASCADE CONSTRAINTS;
DROP TABLE notifications CASCADE CONSTRAINTS;
DROP TABLE attendance_records CASCADE CONSTRAINTS;
DROP TABLE training_registrations CASCADE CONSTRAINTS;
DROP TABLE quiz_attempts CASCADE CONSTRAINTS;
DROP TABLE quiz_assignments CASCADE CONSTRAINTS;
DROP TABLE training_sessions CASCADE CONSTRAINTS;
DROP TABLE quiz_questions CASCADE CONSTRAINTS;
DROP TABLE quizzes CASCADE CONSTRAINTS;
DROP TABLE questions CASCADE CONSTRAINTS;
DROP TABLE class_admins CASCADE CONSTRAINTS;
DROP TABLE class_trainers CASCADE CONSTRAINTS;
DROP TABLE classes CASCADE CONSTRAINTS;
DROP TABLE training_program_syllabuses CASCADE CONSTRAINTS;
DROP TABLE training_programs CASCADE CONSTRAINTS;
DROP TABLE material_files CASCADE CONSTRAINTS;
DROP TABLE syllabus_topics CASCADE CONSTRAINTS;
DROP TABLE syllabus_units CASCADE CONSTRAINTS;
DROP TABLE syllabus_days CASCADE CONSTRAINTS;
DROP TABLE syllabus_output_standards CASCADE CONSTRAINTS;
DROP TABLE syllabuses CASCADE CONSTRAINTS;
DROP TABLE permissions CASCADE CONSTRAINTS;
DROP TABLE user_roles CASCADE CONSTRAINTS;
DROP TABLE roles CASCADE CONSTRAINTS;
DROP TABLE users CASCADE CONSTRAINTS;
